---
# Headplane configuration
server:
  host: "0.0.0.0"
  port: 443
  tls:
    cert_file: "/etc/headplane/tls/cert.pem"
    key_file: "/etc/headplane/tls/key.pem"
  
# Headscale connection
headscale:
  url: "http://headscale:8080"
  api_key: ""  # Set this to your Headscale API key
  
# Authentication
auth:
  method: "headscale"  # or "oidc"
  
# Logging
log:
  level: "info"
  format: "text"
  
# Web interface
web:
  enabled: true
  path: "/web"
