targets:
  $default:
    sources:
      - lib/**
      - pubspec.*
      - $package$
    builders:
      # Hive
      hive_generator:
        enabled: true
      # JSON Serializable
      json_serializable:
        enabled: true
        options:
          explicit_to_json: true
          include_if_null: false

      # Retrofit
      retrofit_generator:
        enabled: true
