name: lunasea
version: 11.0.0
confinement: strict
base: core22
# Required but managed manually via Snapcraft dashboard
summary: summary
description: description
slots:
  dbus-lunasea:
    interface: dbus
    bus: session
    name: app.lunasea.lunasea
apps:
  lunasea:
    command: lunasea
    extensions:
    - gnome
    plugs:
    - home
    - network
    slots:
    - dbus-lunasea
parts:
  zenity:
    plugin: nil
    stage-packages:
    - zenity
  lunasea:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
