name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2

      - run: make lint

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ""
          POSTGRES_HOST_AUTH_METHOD: "trust"
          POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2

      - run: make test
        shell: bash
        env:
          HARDCOVER_API_KEY: ${{ secrets.HARDCOVER_API_KEY }}
          GR_HOST: ${{ secrets.GR_HOST }}
          GR_TEST_COOKIE: ${{ secrets.GR_TEST_COOKIE }}

      - uses: codecov/codecov-action@v5.4.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  ok:
    name: OK
    runs-on: ubuntu-latest
    needs: [lint, test]

    if: always()
    steps:
      - run: exit 1
        if: >-
          needs.lint.result != 'success' ||
          needs.test.result != 'success'

      - run: exit 0
