// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package gr

import (
	"context"
	"encoding/json"

	"github.com/Khan/genqlient/graphql"
)

// BookInfo includes the GraphQL fields of Book requested by the fragment BookInfo.
type BookInfo struct {
	Id                     string                                            `json:"id"`
	LegacyId               int64                                             `json:"legacyId"`
	Description            string                                            `json:"description"`
	BookGenres             []BookInfoBookGenresBookGenre                     `json:"bookGenres"`
	BookSeries             []BookInfoBookSeries                              `json:"bookSeries"`
	Details                BookInfoDetailsBookDetails                        `json:"details"`
	ImageUrl               string                                            `json:"imageUrl"`
	PrimaryContributorEdge BookInfoPrimaryContributorEdgeBookContributorEdge `json:"primaryContributorEdge"`
	Stats                  BookInfoStatsBookOrWorkStats                      `json:"stats"`
	Title                  string                                            `json:"title"`
	TitlePrimary           string                                            `json:"titlePrimary"`
	WebUrl                 string                                            `json:"webUrl"`
}

// GetId returns BookInfo.Id, and is useful for accessing the field via an interface.
func (v *BookInfo) GetId() string { return v.Id }

// GetLegacyId returns BookInfo.LegacyId, and is useful for accessing the field via an interface.
func (v *BookInfo) GetLegacyId() int64 { return v.LegacyId }

// GetDescription returns BookInfo.Description, and is useful for accessing the field via an interface.
func (v *BookInfo) GetDescription() string { return v.Description }

// GetBookGenres returns BookInfo.BookGenres, and is useful for accessing the field via an interface.
func (v *BookInfo) GetBookGenres() []BookInfoBookGenresBookGenre { return v.BookGenres }

// GetBookSeries returns BookInfo.BookSeries, and is useful for accessing the field via an interface.
func (v *BookInfo) GetBookSeries() []BookInfoBookSeries { return v.BookSeries }

// GetDetails returns BookInfo.Details, and is useful for accessing the field via an interface.
func (v *BookInfo) GetDetails() BookInfoDetailsBookDetails { return v.Details }

// GetImageUrl returns BookInfo.ImageUrl, and is useful for accessing the field via an interface.
func (v *BookInfo) GetImageUrl() string { return v.ImageUrl }

// GetPrimaryContributorEdge returns BookInfo.PrimaryContributorEdge, and is useful for accessing the field via an interface.
func (v *BookInfo) GetPrimaryContributorEdge() BookInfoPrimaryContributorEdgeBookContributorEdge {
	return v.PrimaryContributorEdge
}

// GetStats returns BookInfo.Stats, and is useful for accessing the field via an interface.
func (v *BookInfo) GetStats() BookInfoStatsBookOrWorkStats { return v.Stats }

// GetTitle returns BookInfo.Title, and is useful for accessing the field via an interface.
func (v *BookInfo) GetTitle() string { return v.Title }

// GetTitlePrimary returns BookInfo.TitlePrimary, and is useful for accessing the field via an interface.
func (v *BookInfo) GetTitlePrimary() string { return v.TitlePrimary }

// GetWebUrl returns BookInfo.WebUrl, and is useful for accessing the field via an interface.
func (v *BookInfo) GetWebUrl() string { return v.WebUrl }

// BookInfoBookGenresBookGenre includes the requested fields of the GraphQL type BookGenre.
type BookInfoBookGenresBookGenre struct {
	Genre BookInfoBookGenresBookGenreGenre `json:"genre"`
}

// GetGenre returns BookInfoBookGenresBookGenre.Genre, and is useful for accessing the field via an interface.
func (v *BookInfoBookGenresBookGenre) GetGenre() BookInfoBookGenresBookGenreGenre { return v.Genre }

// BookInfoBookGenresBookGenreGenre includes the requested fields of the GraphQL type Genre.
type BookInfoBookGenresBookGenreGenre struct {
	Name string `json:"name"`
}

// GetName returns BookInfoBookGenresBookGenreGenre.Name, and is useful for accessing the field via an interface.
func (v *BookInfoBookGenresBookGenreGenre) GetName() string { return v.Name }

// BookInfoBookSeries includes the requested fields of the GraphQL type BookSeries.
type BookInfoBookSeries struct {
	Series          BookInfoBookSeriesSeries `json:"series"`
	SeriesPlacement string                   `json:"seriesPlacement"`
}

// GetSeries returns BookInfoBookSeries.Series, and is useful for accessing the field via an interface.
func (v *BookInfoBookSeries) GetSeries() BookInfoBookSeriesSeries { return v.Series }

// GetSeriesPlacement returns BookInfoBookSeries.SeriesPlacement, and is useful for accessing the field via an interface.
func (v *BookInfoBookSeries) GetSeriesPlacement() string { return v.SeriesPlacement }

// BookInfoBookSeriesSeries includes the requested fields of the GraphQL type Series.
type BookInfoBookSeriesSeries struct {
	Id     string `json:"id"`
	Title  string `json:"title"`
	WebUrl string `json:"webUrl"`
}

// GetId returns BookInfoBookSeriesSeries.Id, and is useful for accessing the field via an interface.
func (v *BookInfoBookSeriesSeries) GetId() string { return v.Id }

// GetTitle returns BookInfoBookSeriesSeries.Title, and is useful for accessing the field via an interface.
func (v *BookInfoBookSeriesSeries) GetTitle() string { return v.Title }

// GetWebUrl returns BookInfoBookSeriesSeries.WebUrl, and is useful for accessing the field via an interface.
func (v *BookInfoBookSeriesSeries) GetWebUrl() string { return v.WebUrl }

// BookInfoDetailsBookDetails includes the requested fields of the GraphQL type BookDetails.
type BookInfoDetailsBookDetails struct {
	Asin            string                             `json:"asin"`
	Isbn13          string                             `json:"isbn13"`
	Format          string                             `json:"format"`
	NumPages        int64                              `json:"numPages"`
	Language        BookInfoDetailsBookDetailsLanguage `json:"language"`
	OfficialUrl     string                             `json:"officialUrl"`
	Publisher       string                             `json:"publisher"`
	PublicationTime float64                            `json:"publicationTime"`
}

// GetAsin returns BookInfoDetailsBookDetails.Asin, and is useful for accessing the field via an interface.
func (v *BookInfoDetailsBookDetails) GetAsin() string { return v.Asin }

// GetIsbn13 returns BookInfoDetailsBookDetails.Isbn13, and is useful for accessing the field via an interface.
func (v *BookInfoDetailsBookDetails) GetIsbn13() string { return v.Isbn13 }

// GetFormat returns BookInfoDetailsBookDetails.Format, and is useful for accessing the field via an interface.
func (v *BookInfoDetailsBookDetails) GetFormat() string { return v.Format }

// GetNumPages returns BookInfoDetailsBookDetails.NumPages, and is useful for accessing the field via an interface.
func (v *BookInfoDetailsBookDetails) GetNumPages() int64 { return v.NumPages }

// GetLanguage returns BookInfoDetailsBookDetails.Language, and is useful for accessing the field via an interface.
func (v *BookInfoDetailsBookDetails) GetLanguage() BookInfoDetailsBookDetailsLanguage {
	return v.Language
}

// GetOfficialUrl returns BookInfoDetailsBookDetails.OfficialUrl, and is useful for accessing the field via an interface.
func (v *BookInfoDetailsBookDetails) GetOfficialUrl() string { return v.OfficialUrl }

// GetPublisher returns BookInfoDetailsBookDetails.Publisher, and is useful for accessing the field via an interface.
func (v *BookInfoDetailsBookDetails) GetPublisher() string { return v.Publisher }

// GetPublicationTime returns BookInfoDetailsBookDetails.PublicationTime, and is useful for accessing the field via an interface.
func (v *BookInfoDetailsBookDetails) GetPublicationTime() float64 { return v.PublicationTime }

// BookInfoDetailsBookDetailsLanguage includes the requested fields of the GraphQL type Language.
type BookInfoDetailsBookDetailsLanguage struct {
	Name string `json:"name"`
}

// GetName returns BookInfoDetailsBookDetailsLanguage.Name, and is useful for accessing the field via an interface.
func (v *BookInfoDetailsBookDetailsLanguage) GetName() string { return v.Name }

// BookInfoPrimaryContributorEdgeBookContributorEdge includes the requested fields of the GraphQL type BookContributorEdge.
type BookInfoPrimaryContributorEdgeBookContributorEdge struct {
	Node BookInfoPrimaryContributorEdgeBookContributorEdgeNodeContributor `json:"node"`
}

// GetNode returns BookInfoPrimaryContributorEdgeBookContributorEdge.Node, and is useful for accessing the field via an interface.
func (v *BookInfoPrimaryContributorEdgeBookContributorEdge) GetNode() BookInfoPrimaryContributorEdgeBookContributorEdgeNodeContributor {
	return v.Node
}

// BookInfoPrimaryContributorEdgeBookContributorEdgeNodeContributor includes the requested fields of the GraphQL type Contributor.
type BookInfoPrimaryContributorEdgeBookContributorEdgeNodeContributor struct {
	Id              string `json:"id"`
	Name            string `json:"name"`
	LegacyId        int64  `json:"legacyId"`
	WebUrl          string `json:"webUrl"`
	ProfileImageUrl string `json:"profileImageUrl"`
	Description     string `json:"description"`
}

// GetId returns BookInfoPrimaryContributorEdgeBookContributorEdgeNodeContributor.Id, and is useful for accessing the field via an interface.
func (v *BookInfoPrimaryContributorEdgeBookContributorEdgeNodeContributor) GetId() string {
	return v.Id
}

// GetName returns BookInfoPrimaryContributorEdgeBookContributorEdgeNodeContributor.Name, and is useful for accessing the field via an interface.
func (v *BookInfoPrimaryContributorEdgeBookContributorEdgeNodeContributor) GetName() string {
	return v.Name
}

// GetLegacyId returns BookInfoPrimaryContributorEdgeBookContributorEdgeNodeContributor.LegacyId, and is useful for accessing the field via an interface.
func (v *BookInfoPrimaryContributorEdgeBookContributorEdgeNodeContributor) GetLegacyId() int64 {
	return v.LegacyId
}

// GetWebUrl returns BookInfoPrimaryContributorEdgeBookContributorEdgeNodeContributor.WebUrl, and is useful for accessing the field via an interface.
func (v *BookInfoPrimaryContributorEdgeBookContributorEdgeNodeContributor) GetWebUrl() string {
	return v.WebUrl
}

// GetProfileImageUrl returns BookInfoPrimaryContributorEdgeBookContributorEdgeNodeContributor.ProfileImageUrl, and is useful for accessing the field via an interface.
func (v *BookInfoPrimaryContributorEdgeBookContributorEdgeNodeContributor) GetProfileImageUrl() string {
	return v.ProfileImageUrl
}

// GetDescription returns BookInfoPrimaryContributorEdgeBookContributorEdgeNodeContributor.Description, and is useful for accessing the field via an interface.
func (v *BookInfoPrimaryContributorEdgeBookContributorEdgeNodeContributor) GetDescription() string {
	return v.Description
}

// BookInfoStatsBookOrWorkStats includes the requested fields of the GraphQL type BookOrWorkStats.
type BookInfoStatsBookOrWorkStats struct {
	AverageRating float64 `json:"averageRating"`
	RatingsCount  int64   `json:"ratingsCount"`
	RatingsSum    int64   `json:"ratingsSum"`
}

// GetAverageRating returns BookInfoStatsBookOrWorkStats.AverageRating, and is useful for accessing the field via an interface.
func (v *BookInfoStatsBookOrWorkStats) GetAverageRating() float64 { return v.AverageRating }

// GetRatingsCount returns BookInfoStatsBookOrWorkStats.RatingsCount, and is useful for accessing the field via an interface.
func (v *BookInfoStatsBookOrWorkStats) GetRatingsCount() int64 { return v.RatingsCount }

// GetRatingsSum returns BookInfoStatsBookOrWorkStats.RatingsSum, and is useful for accessing the field via an interface.
func (v *BookInfoStatsBookOrWorkStats) GetRatingsSum() int64 { return v.RatingsSum }

// GetAuthorWorksGetWorksByContributorContributorWorksConnection includes the requested fields of the GraphQL type ContributorWorksConnection.
type GetAuthorWorksGetWorksByContributorContributorWorksConnection struct {
	Edges    []GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdge `json:"edges"`
	PageInfo GetAuthorWorksGetWorksByContributorContributorWorksConnectionPageInfo                    `json:"pageInfo"`
}

// GetEdges returns GetAuthorWorksGetWorksByContributorContributorWorksConnection.Edges, and is useful for accessing the field via an interface.
func (v *GetAuthorWorksGetWorksByContributorContributorWorksConnection) GetEdges() []GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdge {
	return v.Edges
}

// GetPageInfo returns GetAuthorWorksGetWorksByContributorContributorWorksConnection.PageInfo, and is useful for accessing the field via an interface.
func (v *GetAuthorWorksGetWorksByContributorContributorWorksConnection) GetPageInfo() GetAuthorWorksGetWorksByContributorContributorWorksConnectionPageInfo {
	return v.PageInfo
}

// GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdge includes the requested fields of the GraphQL type ContributorWorksEdge.
type GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdge struct {
	Node GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdgeNodeWork `json:"node"`
}

// GetNode returns GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdge.Node, and is useful for accessing the field via an interface.
func (v *GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdge) GetNode() GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdgeNodeWork {
	return v.Node
}

// GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdgeNodeWork includes the requested fields of the GraphQL type Work.
type GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdgeNodeWork struct {
	Id       string                                                                                                 `json:"id"`
	BestBook GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdgeNodeWorkBestBook `json:"bestBook"`
}

// GetId returns GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdgeNodeWork.Id, and is useful for accessing the field via an interface.
func (v *GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdgeNodeWork) GetId() string {
	return v.Id
}

// GetBestBook returns GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdgeNodeWork.BestBook, and is useful for accessing the field via an interface.
func (v *GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdgeNodeWork) GetBestBook() GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdgeNodeWorkBestBook {
	return v.BestBook
}

// GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdgeNodeWorkBestBook includes the requested fields of the GraphQL type Book.
type GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdgeNodeWorkBestBook struct {
	LegacyId                  int64                                                                                                                                                `json:"legacyId"`
	PrimaryContributorEdge    GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdgeNodeWorkBestBookPrimaryContributorEdgeBookContributorEdge      `json:"primaryContributorEdge"`
	SecondaryContributorEdges []GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdgeNodeWorkBestBookSecondaryContributorEdgesBookContributorEdge `json:"secondaryContributorEdges"`
}

// GetLegacyId returns GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdgeNodeWorkBestBook.LegacyId, and is useful for accessing the field via an interface.
func (v *GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdgeNodeWorkBestBook) GetLegacyId() int64 {
	return v.LegacyId
}

// GetPrimaryContributorEdge returns GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdgeNodeWorkBestBook.PrimaryContributorEdge, and is useful for accessing the field via an interface.
func (v *GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdgeNodeWorkBestBook) GetPrimaryContributorEdge() GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdgeNodeWorkBestBookPrimaryContributorEdgeBookContributorEdge {
	return v.PrimaryContributorEdge
}

// GetSecondaryContributorEdges returns GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdgeNodeWorkBestBook.SecondaryContributorEdges, and is useful for accessing the field via an interface.
func (v *GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdgeNodeWorkBestBook) GetSecondaryContributorEdges() []GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdgeNodeWorkBestBookSecondaryContributorEdgesBookContributorEdge {
	return v.SecondaryContributorEdges
}

// GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdgeNodeWorkBestBookPrimaryContributorEdgeBookContributorEdge includes the requested fields of the GraphQL type BookContributorEdge.
type GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdgeNodeWorkBestBookPrimaryContributorEdgeBookContributorEdge struct {
	Role string                                                                                                                                                         `json:"role"`
	Node GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdgeNodeWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor `json:"node"`
}

// GetRole returns GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdgeNodeWorkBestBookPrimaryContributorEdgeBookContributorEdge.Role, and is useful for accessing the field via an interface.
func (v *GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdgeNodeWorkBestBookPrimaryContributorEdgeBookContributorEdge) GetRole() string {
	return v.Role
}

// GetNode returns GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdgeNodeWorkBestBookPrimaryContributorEdgeBookContributorEdge.Node, and is useful for accessing the field via an interface.
func (v *GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdgeNodeWorkBestBookPrimaryContributorEdgeBookContributorEdge) GetNode() GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdgeNodeWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor {
	return v.Node
}

// GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdgeNodeWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor includes the requested fields of the GraphQL type Contributor.
type GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdgeNodeWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor struct {
	LegacyId int64 `json:"legacyId"`
}

// GetLegacyId returns GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdgeNodeWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor.LegacyId, and is useful for accessing the field via an interface.
func (v *GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdgeNodeWorkBestBookPrimaryContributorEdgeBookContributorEdgeNodeContributor) GetLegacyId() int64 {
	return v.LegacyId
}

// GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdgeNodeWorkBestBookSecondaryContributorEdgesBookContributorEdge includes the requested fields of the GraphQL type BookContributorEdge.
type GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdgeNodeWorkBestBookSecondaryContributorEdgesBookContributorEdge struct {
	Role string `json:"role"`
}

// GetRole returns GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdgeNodeWorkBestBookSecondaryContributorEdgesBookContributorEdge.Role, and is useful for accessing the field via an interface.
func (v *GetAuthorWorksGetWorksByContributorContributorWorksConnectionEdgesContributorWorksEdgeNodeWorkBestBookSecondaryContributorEdgesBookContributorEdge) GetRole() string {
	return v.Role
}

// GetAuthorWorksGetWorksByContributorContributorWorksConnectionPageInfo includes the requested fields of the GraphQL type PageInfo.
type GetAuthorWorksGetWorksByContributorContributorWorksConnectionPageInfo struct {
	HasNextPage   bool   `json:"hasNextPage"`
	NextPageToken string `json:"nextPageToken"`
}

// GetHasNextPage returns GetAuthorWorksGetWorksByContributorContributorWorksConnectionPageInfo.HasNextPage, and is useful for accessing the field via an interface.
func (v *GetAuthorWorksGetWorksByContributorContributorWorksConnectionPageInfo) GetHasNextPage() bool {
	return v.HasNextPage
}

// GetNextPageToken returns GetAuthorWorksGetWorksByContributorContributorWorksConnectionPageInfo.NextPageToken, and is useful for accessing the field via an interface.
func (v *GetAuthorWorksGetWorksByContributorContributorWorksConnectionPageInfo) GetNextPageToken() string {
	return v.NextPageToken
}

// GetAuthorWorksResponse is returned by GetAuthorWorks on success.
type GetAuthorWorksResponse struct {
	GetWorksByContributor GetAuthorWorksGetWorksByContributorContributorWorksConnection `json:"getWorksByContributor"`
}

// GetGetWorksByContributor returns GetAuthorWorksResponse.GetWorksByContributor, and is useful for accessing the field via an interface.
func (v *GetAuthorWorksResponse) GetGetWorksByContributor() GetAuthorWorksGetWorksByContributorContributorWorksConnection {
	return v.GetWorksByContributor
}

// GetBookGetBookByLegacyIdBook includes the requested fields of the GraphQL type Book.
type GetBookGetBookByLegacyIdBook struct {
	BookInfo `json:"-"`
	Work     GetBookGetBookByLegacyIdBookWork `json:"work"`
}

// GetWork returns GetBookGetBookByLegacyIdBook.Work, and is useful for accessing the field via an interface.
func (v *GetBookGetBookByLegacyIdBook) GetWork() GetBookGetBookByLegacyIdBookWork { return v.Work }

// GetId returns GetBookGetBookByLegacyIdBook.Id, and is useful for accessing the field via an interface.
func (v *GetBookGetBookByLegacyIdBook) GetId() string { return v.BookInfo.Id }

// GetLegacyId returns GetBookGetBookByLegacyIdBook.LegacyId, and is useful for accessing the field via an interface.
func (v *GetBookGetBookByLegacyIdBook) GetLegacyId() int64 { return v.BookInfo.LegacyId }

// GetDescription returns GetBookGetBookByLegacyIdBook.Description, and is useful for accessing the field via an interface.
func (v *GetBookGetBookByLegacyIdBook) GetDescription() string { return v.BookInfo.Description }

// GetBookGenres returns GetBookGetBookByLegacyIdBook.BookGenres, and is useful for accessing the field via an interface.
func (v *GetBookGetBookByLegacyIdBook) GetBookGenres() []BookInfoBookGenresBookGenre {
	return v.BookInfo.BookGenres
}

// GetBookSeries returns GetBookGetBookByLegacyIdBook.BookSeries, and is useful for accessing the field via an interface.
func (v *GetBookGetBookByLegacyIdBook) GetBookSeries() []BookInfoBookSeries {
	return v.BookInfo.BookSeries
}

// GetDetails returns GetBookGetBookByLegacyIdBook.Details, and is useful for accessing the field via an interface.
func (v *GetBookGetBookByLegacyIdBook) GetDetails() BookInfoDetailsBookDetails {
	return v.BookInfo.Details
}

// GetImageUrl returns GetBookGetBookByLegacyIdBook.ImageUrl, and is useful for accessing the field via an interface.
func (v *GetBookGetBookByLegacyIdBook) GetImageUrl() string { return v.BookInfo.ImageUrl }

// GetPrimaryContributorEdge returns GetBookGetBookByLegacyIdBook.PrimaryContributorEdge, and is useful for accessing the field via an interface.
func (v *GetBookGetBookByLegacyIdBook) GetPrimaryContributorEdge() BookInfoPrimaryContributorEdgeBookContributorEdge {
	return v.BookInfo.PrimaryContributorEdge
}

// GetStats returns GetBookGetBookByLegacyIdBook.Stats, and is useful for accessing the field via an interface.
func (v *GetBookGetBookByLegacyIdBook) GetStats() BookInfoStatsBookOrWorkStats {
	return v.BookInfo.Stats
}

// GetTitle returns GetBookGetBookByLegacyIdBook.Title, and is useful for accessing the field via an interface.
func (v *GetBookGetBookByLegacyIdBook) GetTitle() string { return v.BookInfo.Title }

// GetTitlePrimary returns GetBookGetBookByLegacyIdBook.TitlePrimary, and is useful for accessing the field via an interface.
func (v *GetBookGetBookByLegacyIdBook) GetTitlePrimary() string { return v.BookInfo.TitlePrimary }

// GetWebUrl returns GetBookGetBookByLegacyIdBook.WebUrl, and is useful for accessing the field via an interface.
func (v *GetBookGetBookByLegacyIdBook) GetWebUrl() string { return v.BookInfo.WebUrl }

func (v *GetBookGetBookByLegacyIdBook) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*GetBookGetBookByLegacyIdBook
		graphql.NoUnmarshalJSON
	}
	firstPass.GetBookGetBookByLegacyIdBook = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	err = json.Unmarshal(
		b, &v.BookInfo)
	if err != nil {
		return err
	}
	return nil
}

type __premarshalGetBookGetBookByLegacyIdBook struct {
	Work GetBookGetBookByLegacyIdBookWork `json:"work"`

	Id string `json:"id"`

	LegacyId int64 `json:"legacyId"`

	Description string `json:"description"`

	BookGenres []BookInfoBookGenresBookGenre `json:"bookGenres"`

	BookSeries []BookInfoBookSeries `json:"bookSeries"`

	Details BookInfoDetailsBookDetails `json:"details"`

	ImageUrl string `json:"imageUrl"`

	PrimaryContributorEdge BookInfoPrimaryContributorEdgeBookContributorEdge `json:"primaryContributorEdge"`

	Stats BookInfoStatsBookOrWorkStats `json:"stats"`

	Title string `json:"title"`

	TitlePrimary string `json:"titlePrimary"`

	WebUrl string `json:"webUrl"`
}

func (v *GetBookGetBookByLegacyIdBook) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *GetBookGetBookByLegacyIdBook) __premarshalJSON() (*__premarshalGetBookGetBookByLegacyIdBook, error) {
	var retval __premarshalGetBookGetBookByLegacyIdBook

	retval.Work = v.Work
	retval.Id = v.BookInfo.Id
	retval.LegacyId = v.BookInfo.LegacyId
	retval.Description = v.BookInfo.Description
	retval.BookGenres = v.BookInfo.BookGenres
	retval.BookSeries = v.BookInfo.BookSeries
	retval.Details = v.BookInfo.Details
	retval.ImageUrl = v.BookInfo.ImageUrl
	retval.PrimaryContributorEdge = v.BookInfo.PrimaryContributorEdge
	retval.Stats = v.BookInfo.Stats
	retval.Title = v.BookInfo.Title
	retval.TitlePrimary = v.BookInfo.TitlePrimary
	retval.WebUrl = v.BookInfo.WebUrl
	return &retval, nil
}

// GetBookGetBookByLegacyIdBookWork includes the requested fields of the GraphQL type Work.
type GetBookGetBookByLegacyIdBookWork struct {
	Id       string                                                  `json:"id"`
	LegacyId int64                                                   `json:"legacyId"`
	Details  GetBookGetBookByLegacyIdBookWorkDetails                 `json:"details"`
	BestBook GetBookGetBookByLegacyIdBookWorkBestBook                `json:"bestBook"`
	Editions GetBookGetBookByLegacyIdBookWorkEditionsBooksConnection `json:"editions"`
}

// GetId returns GetBookGetBookByLegacyIdBookWork.Id, and is useful for accessing the field via an interface.
func (v *GetBookGetBookByLegacyIdBookWork) GetId() string { return v.Id }

// GetLegacyId returns GetBookGetBookByLegacyIdBookWork.LegacyId, and is useful for accessing the field via an interface.
func (v *GetBookGetBookByLegacyIdBookWork) GetLegacyId() int64 { return v.LegacyId }

// GetDetails returns GetBookGetBookByLegacyIdBookWork.Details, and is useful for accessing the field via an interface.
func (v *GetBookGetBookByLegacyIdBookWork) GetDetails() GetBookGetBookByLegacyIdBookWorkDetails {
	return v.Details
}

// GetBestBook returns GetBookGetBookByLegacyIdBookWork.BestBook, and is useful for accessing the field via an interface.
func (v *GetBookGetBookByLegacyIdBookWork) GetBestBook() GetBookGetBookByLegacyIdBookWorkBestBook {
	return v.BestBook
}

// GetEditions returns GetBookGetBookByLegacyIdBookWork.Editions, and is useful for accessing the field via an interface.
func (v *GetBookGetBookByLegacyIdBookWork) GetEditions() GetBookGetBookByLegacyIdBookWorkEditionsBooksConnection {
	return v.Editions
}

// GetBookGetBookByLegacyIdBookWorkBestBook includes the requested fields of the GraphQL type Book.
type GetBookGetBookByLegacyIdBookWorkBestBook struct {
	LegacyId     int64  `json:"legacyId"`
	Title        string `json:"title"`
	TitlePrimary string `json:"titlePrimary"`
}

// GetLegacyId returns GetBookGetBookByLegacyIdBookWorkBestBook.LegacyId, and is useful for accessing the field via an interface.
func (v *GetBookGetBookByLegacyIdBookWorkBestBook) GetLegacyId() int64 { return v.LegacyId }

// GetTitle returns GetBookGetBookByLegacyIdBookWorkBestBook.Title, and is useful for accessing the field via an interface.
func (v *GetBookGetBookByLegacyIdBookWorkBestBook) GetTitle() string { return v.Title }

// GetTitlePrimary returns GetBookGetBookByLegacyIdBookWorkBestBook.TitlePrimary, and is useful for accessing the field via an interface.
func (v *GetBookGetBookByLegacyIdBookWorkBestBook) GetTitlePrimary() string { return v.TitlePrimary }

// GetBookGetBookByLegacyIdBookWorkDetails includes the requested fields of the GraphQL type WorkDetails.
type GetBookGetBookByLegacyIdBookWorkDetails struct {
	WebUrl          string  `json:"webUrl"`
	PublicationTime float64 `json:"publicationTime"`
}

// GetWebUrl returns GetBookGetBookByLegacyIdBookWorkDetails.WebUrl, and is useful for accessing the field via an interface.
func (v *GetBookGetBookByLegacyIdBookWorkDetails) GetWebUrl() string { return v.WebUrl }

// GetPublicationTime returns GetBookGetBookByLegacyIdBookWorkDetails.PublicationTime, and is useful for accessing the field via an interface.
func (v *GetBookGetBookByLegacyIdBookWorkDetails) GetPublicationTime() float64 {
	return v.PublicationTime
}

// GetBookGetBookByLegacyIdBookWorkEditionsBooksConnection includes the requested fields of the GraphQL type BooksConnection.
type GetBookGetBookByLegacyIdBookWorkEditionsBooksConnection struct {
	Edges []GetBookGetBookByLegacyIdBookWorkEditionsBooksConnectionEdgesBooksEdge `json:"edges"`
}

// GetEdges returns GetBookGetBookByLegacyIdBookWorkEditionsBooksConnection.Edges, and is useful for accessing the field via an interface.
func (v *GetBookGetBookByLegacyIdBookWorkEditionsBooksConnection) GetEdges() []GetBookGetBookByLegacyIdBookWorkEditionsBooksConnectionEdgesBooksEdge {
	return v.Edges
}

// GetBookGetBookByLegacyIdBookWorkEditionsBooksConnectionEdgesBooksEdge includes the requested fields of the GraphQL type BooksEdge.
type GetBookGetBookByLegacyIdBookWorkEditionsBooksConnectionEdgesBooksEdge struct {
	Node GetBookGetBookByLegacyIdBookWorkEditionsBooksConnectionEdgesBooksEdgeNodeBook `json:"node"`
}

// GetNode returns GetBookGetBookByLegacyIdBookWorkEditionsBooksConnectionEdgesBooksEdge.Node, and is useful for accessing the field via an interface.
func (v *GetBookGetBookByLegacyIdBookWorkEditionsBooksConnectionEdgesBooksEdge) GetNode() GetBookGetBookByLegacyIdBookWorkEditionsBooksConnectionEdgesBooksEdgeNodeBook {
	return v.Node
}

// GetBookGetBookByLegacyIdBookWorkEditionsBooksConnectionEdgesBooksEdgeNodeBook includes the requested fields of the GraphQL type Book.
type GetBookGetBookByLegacyIdBookWorkEditionsBooksConnectionEdgesBooksEdgeNodeBook struct {
	BookInfo `json:"-"`
}

// GetId returns GetBookGetBookByLegacyIdBookWorkEditionsBooksConnectionEdgesBooksEdgeNodeBook.Id, and is useful for accessing the field via an interface.
func (v *GetBookGetBookByLegacyIdBookWorkEditionsBooksConnectionEdgesBooksEdgeNodeBook) GetId() string {
	return v.BookInfo.Id
}

// GetLegacyId returns GetBookGetBookByLegacyIdBookWorkEditionsBooksConnectionEdgesBooksEdgeNodeBook.LegacyId, and is useful for accessing the field via an interface.
func (v *GetBookGetBookByLegacyIdBookWorkEditionsBooksConnectionEdgesBooksEdgeNodeBook) GetLegacyId() int64 {
	return v.BookInfo.LegacyId
}

// GetDescription returns GetBookGetBookByLegacyIdBookWorkEditionsBooksConnectionEdgesBooksEdgeNodeBook.Description, and is useful for accessing the field via an interface.
func (v *GetBookGetBookByLegacyIdBookWorkEditionsBooksConnectionEdgesBooksEdgeNodeBook) GetDescription() string {
	return v.BookInfo.Description
}

// GetBookGenres returns GetBookGetBookByLegacyIdBookWorkEditionsBooksConnectionEdgesBooksEdgeNodeBook.BookGenres, and is useful for accessing the field via an interface.
func (v *GetBookGetBookByLegacyIdBookWorkEditionsBooksConnectionEdgesBooksEdgeNodeBook) GetBookGenres() []BookInfoBookGenresBookGenre {
	return v.BookInfo.BookGenres
}

// GetBookSeries returns GetBookGetBookByLegacyIdBookWorkEditionsBooksConnectionEdgesBooksEdgeNodeBook.BookSeries, and is useful for accessing the field via an interface.
func (v *GetBookGetBookByLegacyIdBookWorkEditionsBooksConnectionEdgesBooksEdgeNodeBook) GetBookSeries() []BookInfoBookSeries {
	return v.BookInfo.BookSeries
}

// GetDetails returns GetBookGetBookByLegacyIdBookWorkEditionsBooksConnectionEdgesBooksEdgeNodeBook.Details, and is useful for accessing the field via an interface.
func (v *GetBookGetBookByLegacyIdBookWorkEditionsBooksConnectionEdgesBooksEdgeNodeBook) GetDetails() BookInfoDetailsBookDetails {
	return v.BookInfo.Details
}

// GetImageUrl returns GetBookGetBookByLegacyIdBookWorkEditionsBooksConnectionEdgesBooksEdgeNodeBook.ImageUrl, and is useful for accessing the field via an interface.
func (v *GetBookGetBookByLegacyIdBookWorkEditionsBooksConnectionEdgesBooksEdgeNodeBook) GetImageUrl() string {
	return v.BookInfo.ImageUrl
}

// GetPrimaryContributorEdge returns GetBookGetBookByLegacyIdBookWorkEditionsBooksConnectionEdgesBooksEdgeNodeBook.PrimaryContributorEdge, and is useful for accessing the field via an interface.
func (v *GetBookGetBookByLegacyIdBookWorkEditionsBooksConnectionEdgesBooksEdgeNodeBook) GetPrimaryContributorEdge() BookInfoPrimaryContributorEdgeBookContributorEdge {
	return v.BookInfo.PrimaryContributorEdge
}

// GetStats returns GetBookGetBookByLegacyIdBookWorkEditionsBooksConnectionEdgesBooksEdgeNodeBook.Stats, and is useful for accessing the field via an interface.
func (v *GetBookGetBookByLegacyIdBookWorkEditionsBooksConnectionEdgesBooksEdgeNodeBook) GetStats() BookInfoStatsBookOrWorkStats {
	return v.BookInfo.Stats
}

// GetTitle returns GetBookGetBookByLegacyIdBookWorkEditionsBooksConnectionEdgesBooksEdgeNodeBook.Title, and is useful for accessing the field via an interface.
func (v *GetBookGetBookByLegacyIdBookWorkEditionsBooksConnectionEdgesBooksEdgeNodeBook) GetTitle() string {
	return v.BookInfo.Title
}

// GetTitlePrimary returns GetBookGetBookByLegacyIdBookWorkEditionsBooksConnectionEdgesBooksEdgeNodeBook.TitlePrimary, and is useful for accessing the field via an interface.
func (v *GetBookGetBookByLegacyIdBookWorkEditionsBooksConnectionEdgesBooksEdgeNodeBook) GetTitlePrimary() string {
	return v.BookInfo.TitlePrimary
}

// GetWebUrl returns GetBookGetBookByLegacyIdBookWorkEditionsBooksConnectionEdgesBooksEdgeNodeBook.WebUrl, and is useful for accessing the field via an interface.
func (v *GetBookGetBookByLegacyIdBookWorkEditionsBooksConnectionEdgesBooksEdgeNodeBook) GetWebUrl() string {
	return v.BookInfo.WebUrl
}

func (v *GetBookGetBookByLegacyIdBookWorkEditionsBooksConnectionEdgesBooksEdgeNodeBook) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*GetBookGetBookByLegacyIdBookWorkEditionsBooksConnectionEdgesBooksEdgeNodeBook
		graphql.NoUnmarshalJSON
	}
	firstPass.GetBookGetBookByLegacyIdBookWorkEditionsBooksConnectionEdgesBooksEdgeNodeBook = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	err = json.Unmarshal(
		b, &v.BookInfo)
	if err != nil {
		return err
	}
	return nil
}

type __premarshalGetBookGetBookByLegacyIdBookWorkEditionsBooksConnectionEdgesBooksEdgeNodeBook struct {
	Id string `json:"id"`

	LegacyId int64 `json:"legacyId"`

	Description string `json:"description"`

	BookGenres []BookInfoBookGenresBookGenre `json:"bookGenres"`

	BookSeries []BookInfoBookSeries `json:"bookSeries"`

	Details BookInfoDetailsBookDetails `json:"details"`

	ImageUrl string `json:"imageUrl"`

	PrimaryContributorEdge BookInfoPrimaryContributorEdgeBookContributorEdge `json:"primaryContributorEdge"`

	Stats BookInfoStatsBookOrWorkStats `json:"stats"`

	Title string `json:"title"`

	TitlePrimary string `json:"titlePrimary"`

	WebUrl string `json:"webUrl"`
}

func (v *GetBookGetBookByLegacyIdBookWorkEditionsBooksConnectionEdgesBooksEdgeNodeBook) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *GetBookGetBookByLegacyIdBookWorkEditionsBooksConnectionEdgesBooksEdgeNodeBook) __premarshalJSON() (*__premarshalGetBookGetBookByLegacyIdBookWorkEditionsBooksConnectionEdgesBooksEdgeNodeBook, error) {
	var retval __premarshalGetBookGetBookByLegacyIdBookWorkEditionsBooksConnectionEdgesBooksEdgeNodeBook

	retval.Id = v.BookInfo.Id
	retval.LegacyId = v.BookInfo.LegacyId
	retval.Description = v.BookInfo.Description
	retval.BookGenres = v.BookInfo.BookGenres
	retval.BookSeries = v.BookInfo.BookSeries
	retval.Details = v.BookInfo.Details
	retval.ImageUrl = v.BookInfo.ImageUrl
	retval.PrimaryContributorEdge = v.BookInfo.PrimaryContributorEdge
	retval.Stats = v.BookInfo.Stats
	retval.Title = v.BookInfo.Title
	retval.TitlePrimary = v.BookInfo.TitlePrimary
	retval.WebUrl = v.BookInfo.WebUrl
	return &retval, nil
}

// GetBookResponse is returned by GetBook on success.
type GetBookResponse struct {
	GetBookByLegacyId GetBookGetBookByLegacyIdBook `json:"getBookByLegacyId"`
}

// GetGetBookByLegacyId returns GetBookResponse.GetBookByLegacyId, and is useful for accessing the field via an interface.
func (v *GetBookResponse) GetGetBookByLegacyId() GetBookGetBookByLegacyIdBook {
	return v.GetBookByLegacyId
}

// GetEditionsGetEditionsBooksConnection includes the requested fields of the GraphQL type BooksConnection.
type GetEditionsGetEditionsBooksConnection struct {
	Edges    []GetEditionsGetEditionsBooksConnectionEdgesBooksEdge `json:"edges"`
	PageInfo GetEditionsGetEditionsBooksConnectionPageInfo         `json:"pageInfo"`
}

// GetEdges returns GetEditionsGetEditionsBooksConnection.Edges, and is useful for accessing the field via an interface.
func (v *GetEditionsGetEditionsBooksConnection) GetEdges() []GetEditionsGetEditionsBooksConnectionEdgesBooksEdge {
	return v.Edges
}

// GetPageInfo returns GetEditionsGetEditionsBooksConnection.PageInfo, and is useful for accessing the field via an interface.
func (v *GetEditionsGetEditionsBooksConnection) GetPageInfo() GetEditionsGetEditionsBooksConnectionPageInfo {
	return v.PageInfo
}

// GetEditionsGetEditionsBooksConnectionEdgesBooksEdge includes the requested fields of the GraphQL type BooksEdge.
type GetEditionsGetEditionsBooksConnectionEdgesBooksEdge struct {
	Node GetEditionsGetEditionsBooksConnectionEdgesBooksEdgeNodeBook `json:"node"`
}

// GetNode returns GetEditionsGetEditionsBooksConnectionEdgesBooksEdge.Node, and is useful for accessing the field via an interface.
func (v *GetEditionsGetEditionsBooksConnectionEdgesBooksEdge) GetNode() GetEditionsGetEditionsBooksConnectionEdgesBooksEdgeNodeBook {
	return v.Node
}

// GetEditionsGetEditionsBooksConnectionEdgesBooksEdgeNodeBook includes the requested fields of the GraphQL type Book.
type GetEditionsGetEditionsBooksConnectionEdgesBooksEdgeNodeBook struct {
	Id       string `json:"id"`
	LegacyId int64  `json:"legacyId"`
}

// GetId returns GetEditionsGetEditionsBooksConnectionEdgesBooksEdgeNodeBook.Id, and is useful for accessing the field via an interface.
func (v *GetEditionsGetEditionsBooksConnectionEdgesBooksEdgeNodeBook) GetId() string { return v.Id }

// GetLegacyId returns GetEditionsGetEditionsBooksConnectionEdgesBooksEdgeNodeBook.LegacyId, and is useful for accessing the field via an interface.
func (v *GetEditionsGetEditionsBooksConnectionEdgesBooksEdgeNodeBook) GetLegacyId() int64 {
	return v.LegacyId
}

// GetEditionsGetEditionsBooksConnectionPageInfo includes the requested fields of the GraphQL type PageInfo.
type GetEditionsGetEditionsBooksConnectionPageInfo struct {
	HasNextPage   bool   `json:"hasNextPage"`
	NextPageToken string `json:"nextPageToken"`
}

// GetHasNextPage returns GetEditionsGetEditionsBooksConnectionPageInfo.HasNextPage, and is useful for accessing the field via an interface.
func (v *GetEditionsGetEditionsBooksConnectionPageInfo) GetHasNextPage() bool { return v.HasNextPage }

// GetNextPageToken returns GetEditionsGetEditionsBooksConnectionPageInfo.NextPageToken, and is useful for accessing the field via an interface.
func (v *GetEditionsGetEditionsBooksConnectionPageInfo) GetNextPageToken() string {
	return v.NextPageToken
}

// GetEditionsResponse is returned by GetEditions on success.
type GetEditionsResponse struct {
	GetEditions GetEditionsGetEditionsBooksConnection `json:"getEditions"`
}

// GetGetEditions returns GetEditionsResponse.GetEditions, and is useful for accessing the field via an interface.
func (v *GetEditionsResponse) GetGetEditions() GetEditionsGetEditionsBooksConnection {
	return v.GetEditions
}

type GetWorksByContributorInput struct {
	Id string `json:"id"`
}

// GetId returns GetWorksByContributorInput.Id, and is useful for accessing the field via an interface.
func (v *GetWorksByContributorInput) GetId() string { return v.Id }

type PaginationInput struct {
	After  string `json:"after"`
	Before string `json:"before"`
	Limit  int64  `json:"limit"`
}

// GetAfter returns PaginationInput.After, and is useful for accessing the field via an interface.
func (v *PaginationInput) GetAfter() string { return v.After }

// GetBefore returns PaginationInput.Before, and is useful for accessing the field via an interface.
func (v *PaginationInput) GetBefore() string { return v.Before }

// GetLimit returns PaginationInput.Limit, and is useful for accessing the field via an interface.
func (v *PaginationInput) GetLimit() int64 { return v.Limit }

// __GetAuthorWorksInput is used internally by genqlient
type __GetAuthorWorksInput struct {
	GetWorksByContributorInput GetWorksByContributorInput `json:"getWorksByContributorInput"`
	Pagination                 PaginationInput            `json:"pagination"`
}

// GetGetWorksByContributorInput returns __GetAuthorWorksInput.GetWorksByContributorInput, and is useful for accessing the field via an interface.
func (v *__GetAuthorWorksInput) GetGetWorksByContributorInput() GetWorksByContributorInput {
	return v.GetWorksByContributorInput
}

// GetPagination returns __GetAuthorWorksInput.Pagination, and is useful for accessing the field via an interface.
func (v *__GetAuthorWorksInput) GetPagination() PaginationInput { return v.Pagination }

// __GetBookInput is used internally by genqlient
type __GetBookInput struct {
	LegacyId int64 `json:"legacyId"`
}

// GetLegacyId returns __GetBookInput.LegacyId, and is useful for accessing the field via an interface.
func (v *__GetBookInput) GetLegacyId() int64 { return v.LegacyId }

// __GetEditionsInput is used internally by genqlient
type __GetEditionsInput struct {
	WorkId     string          `json:"workId"`
	Pagination PaginationInput `json:"pagination"`
}

// GetWorkId returns __GetEditionsInput.WorkId, and is useful for accessing the field via an interface.
func (v *__GetEditionsInput) GetWorkId() string { return v.WorkId }

// GetPagination returns __GetEditionsInput.Pagination, and is useful for accessing the field via an interface.
func (v *__GetEditionsInput) GetPagination() PaginationInput { return v.Pagination }

// The query or mutation executed by GetAuthorWorks.
const GetAuthorWorks_Operation = `
query GetAuthorWorks ($getWorksByContributorInput: GetWorksByContributorInput!, $pagination: PaginationInput!) {
	getWorksByContributor(getWorksByContributorInput: $getWorksByContributorInput, pagination: $pagination) {
		edges {
			node {
				id
				bestBook {
					legacyId
					primaryContributorEdge {
						role
						node {
							legacyId
						}
					}
					secondaryContributorEdges {
						role
					}
				}
			}
		}
		pageInfo {
			hasNextPage
			nextPageToken
		}
	}
}
`

func GetAuthorWorks(
	ctx_ context.Context,
	client_ graphql.Client,
	getWorksByContributorInput GetWorksByContributorInput,
	pagination PaginationInput,
) (*GetAuthorWorksResponse, error) {
	req_ := &graphql.Request{
		OpName: "GetAuthorWorks",
		Query:  GetAuthorWorks_Operation,
		Variables: &__GetAuthorWorksInput{
			GetWorksByContributorInput: getWorksByContributorInput,
			Pagination:                 pagination,
		},
	}
	var err_ error

	var data_ GetAuthorWorksResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by GetBook.
const GetBook_Operation = `
query GetBook ($legacyId: Int!) {
	getBookByLegacyId(legacyId: $legacyId) {
		... BookInfo
		work {
			id
			legacyId
			details {
				webUrl
				publicationTime
			}
			bestBook {
				legacyId
				title
				titlePrimary
			}
			editions {
				edges {
					node {
						... BookInfo
					}
				}
			}
		}
	}
}
fragment BookInfo on Book {
	id
	legacyId
	description(stripped: true)
	bookGenres {
		genre {
			name
		}
	}
	bookSeries {
		series {
			id
			title
			webUrl
		}
		seriesPlacement
	}
	details {
		asin
		isbn13
		format
		numPages
		language {
			name
		}
		officialUrl
		publisher
		publicationTime
	}
	imageUrl
	primaryContributorEdge {
		node {
			id
			name
			legacyId
			webUrl
			profileImageUrl
			description
		}
	}
	stats {
		averageRating
		ratingsCount
		ratingsSum
	}
	title
	titlePrimary
	webUrl
}
`

func GetBook(
	ctx_ context.Context,
	client_ graphql.Client,
	legacyId int64,
) (*GetBookResponse, error) {
	req_ := &graphql.Request{
		OpName: "GetBook",
		Query:  GetBook_Operation,
		Variables: &__GetBookInput{
			LegacyId: legacyId,
		},
	}
	var err_ error

	var data_ GetBookResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}

// The query or mutation executed by GetEditions.
const GetEditions_Operation = `
query GetEditions ($workId: ID!, $pagination: PaginationInput!) {
	getEditions(id: $workId, pagination: $pagination) {
		edges {
			node {
				id
				legacyId
			}
		}
		pageInfo {
			hasNextPage
			nextPageToken
		}
	}
}
`

func GetEditions(
	ctx_ context.Context,
	client_ graphql.Client,
	workId string,
	pagination PaginationInput,
) (*GetEditionsResponse, error) {
	req_ := &graphql.Request{
		OpName: "GetEditions",
		Query:  GetEditions_Operation,
		Variables: &__GetEditionsInput{
			WorkId:     workId,
			Pagination: pagination,
		},
	}
	var err_ error

	var data_ GetEditionsResponse
	resp_ := &graphql.Response{Data: &data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return &data_, err_
}
