// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("UserCSSLoader.disabled_list", "");
user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1750738820);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1750740165);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1750738820);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1750738820);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.lastDir", "/home/lou/Downloads");
user_pref("browser.download.panel.shown", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.jxl", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1750652390);
user_pref("browser.laterrun.bookkeeping.sessionCount", 10);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 148);
user_pref("browser.newtabpage.activity-stream.impressionId", "{c41ef140-1efc-4892-a7b9-987b1dacccb8}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\",\"_1018e4d6-728f-4b20-ad56-37578a4de76b_\"],\"idsInUrlbar\":[\"_1018e4d6-728f-4b20-ad56-37578a4de76b_\",\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.policies.runOncePerModification.extensionsInstall", "[\"https://addons.mozilla.org/firefox/downloads/latest/catppuccin-mocha-mauve/latest.xpi\",\"https://addons.mozilla.org/firefox/downloads/latest/darkreader/latest.xpi\",\"https://addons.mozilla.org/firefox/downloads/latest/ublock-origin/latest.xpi\",\"https://addons.mozilla.org/firefox/downloads/latest/flagfox/latest.xpi\"]");
user_pref("browser.policies.runOncePerModification.extensionsUninstall", "[\"google@search.mozilla.org\",\"bing@search.mozilla.org\",\"amazondotcom@search.mozilla.org\",\"ebay@search.mozilla.org\",\"twitter@search.mozilla.org\"]");
user_pref("browser.policies.runOncePerModification.removeSearchEngines", "[\"Bing\",\"Amazon.com\",\"eBay\",\"Twitter\"]");
user_pref("browser.policies.runOncePerModification.setDefaultSearchEngine", "Garuda's searX");
user_pref("browser.region.network.url", "");
user_pref("browser.region.update.enabled", false);
user_pref("browser.safebrowsing.downloads.remote.block_potentially_unwanted", false);
user_pref("browser.safebrowsing.downloads.remote.block_uncommon", false);
user_pref("browser.safebrowsing.downloads.remote.enabled", false);
user_pref("browser.safebrowsing.downloads.remote.url", "");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1750703389");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20250305195922");
user_pref("browser.startup.homepage_override.mstone", "128.9.0");
user_pref("browser.startup.lastColdStartupCheck", 1750703387);
user_pref("browser.tabs.closeTabByDblclick", true);
user_pref("browser.tabs.loadInBackground", false);
user_pref("browser.theme.toolbar-theme", 0);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[\"plasma-browser-integration_kde_org-browser-action\",\"addon_darkreader_org-browser-action\"],\"nav-bar\":[\"undo-closed-tab\",\"back-button\",\"forward-button\",\"sidebar-button\",\"sidebar-reverse-position-toolbar\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\",\"profile-manager\",\"ublock0_raymondhill_net-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"workspaces-toolbar-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\",\"firefox-view-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"statusBar\":[\"screenshot-button\",\"fullscreen-button\",\"status-text\"]},\"seen\":[\"plasma-browser-integration_kde_org-browser-action\",\"developer-button\",\"sidebar-reverse-position-toolbar\",\"undo-closed-tab\",\"profile-manager\",\"addon_darkreader_org-browser-action\",\"workspaces-toolbar-button\",\"ublock0_raymondhill_net-browser-action\"],\"dirtyAreaCache\":[\"unified-extensions-area\",\"nav-bar\",\"statusBar\",\"TabsToolbar\",\"toolbar-menubar\",\"PersonalToolbar\"],\"currentVersion\":20,\"newElementCount\":2}");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("captivedetect.canonicalURL", "");
user_pref("devtools.debugger.remote-enabled", false);
user_pref("distribution.firedragon.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "128.9.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "ebc534fb5d6944d89f7518f24396158a");
user_pref("dom.security.https_only_mode_ever_enabled", true);
user_pref("extensions.activeThemeID", "{d090b7ee-a385-4d54-b9a4-f7164d17756d}");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 36);
user_pref("extensions.formautofill.creditCards.reauth.optout", "MDIEEPgAAAAAAAAAAAAAAAAAAAEwFAYIKoZIhvcNAwcECEleHzxXrz6fBAgo2aXekVMzXw==");
user_pref("extensions.getAddons.cache.lastUpdate", 1750738820);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20250305195922");
user_pref("extensions.lastAppVersion", "128.9.0");
user_pref("extensions.lastPlatformVersion", "128.9.0");
user_pref("extensions.pendingOperations", true);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.addon@darkreader.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.floorp-system@floorp.ablaze.one", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.paxmod@numirias", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.plasma-browser-integration@kde.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.{1018e4d6-728f-4b20-ad56-37578a4de76b}", true);
user_pref("extensions.webextensions.uuids", "{\"floorp-actions@floorp.ablaze.one\":\"a0ba9ef4-bbbe-4936-80ec-5493f0807f22\",\"floorp-system@floorp.ablaze.one\":\"663bd45d-4778-4a2e-ad12-9933714aa4a1\",\"formautofill@mozilla.org\":\"f0d2032c-659a-4da6-a9ea-dda44f29c178\",\"official-site-ua@floorp.ablaze.one\":\"2bccf4de-2160-453d-aa59-35bfc09f7597\",\"paxmod@numirias\":\"87b3c8ec-c32b-4a28-900a-014c33e9924c\",\"pictureinpicture@mozilla.org\":\"b2f6443b-ea20-42ba-947b-e3ebdff98c7f\",\"screenshots@mozilla.org\":\"c4f4f105-7fb5-404c-a96d-10820861c8a7\",\"webcompat@mozilla.org\":\"daa76de1-afdf-4044-a981-2b0c67248d87\",\"webpanel-ua@floorp.ablaze.one\":\"cfe76853-1a62-423c-b39b-52c1a09fd9b6\",\"plasma-browser-integration@kde.org\":\"2518abd8-45a2-4bcc-8372-ca9d938736c8\",\"default-theme@mozilla.org\":\"85f59409-435b-45de-8904-d8c53523d87a\",\"addons-search-detection@mozilla.com\":\"08eee27c-83fa-4016-9afd-7e0c9606940a\",\"{d090b7ee-a385-4d54-b9a4-f7164d17756d}\":\"c57b6db1-241c-4129-adc7-4bd6b05eea12\",\"addon@darkreader.org\":\"c6ec2df9-2b62-475f-95c7-bf066a8f7307\",\"{1018e4d6-728f-4b20-ad56-37578a4de76b}\":\"d69924b6-318f-49fe-822c-daa6000f6c98\",\"uBlock0@raymondhill.net\":\"54069815-a156-4ee0-b450-9d42586fa787\"}");
user_pref("firedragon.cfg.migration.contentBlockingCategoryStrict", true);
user_pref("floorp.browser.nora.csk.data", "{}");
user_pref("floorp.browser.note.backup.latest.time", "1750703387370");
user_pref("floorp.browser.sidebar.is.displayed", false);
user_pref("floorp.startup.oldVersion", "11.24.0-1");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("idle.lastDailyNotification", 1750653281);
user_pref("intl.accept_languages", "en-US, en");
user_pref("javascript.use_us_english_locale", true);
user_pref("media.gmp-manager.buildID", "20250305195922");
user_pref("media.gmp-manager.lastCheck", 1750652435);
user_pref("media.gmp-manager.lastEmptyCheck", 1750652435);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.captive-portal-service.enabled", false);
user_pref("network.connectivity-service.enabled", false);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.predictor.enabled", false);
user_pref("network.prefetch-next", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("permissions.delegation.enabled", false);
user_pref("permissions.manager.defaultsUrl", "");
user_pref("places.database.lastMaintenance", 1750653281);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.globalprivacycontrol.was_ever_enabled", true);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.purge_trackers.last_purge", "1750653281644");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "fce44a26-8da0-44f3-abde-876e6c74d2e6");
user_pref("security.tls.enable_0rtt_data", false);
user_pref("services.sync.engine.addresses.available", true);
user_pref("signon.management.page.os-auth.optout", "MDIEEPgAAAAAAAAAAAAAAAAAAAEwFAYIKoZIhvcNAwcECEYsQky/WqEuBAgySQTWZ1EylA==");
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1750653281);
user_pref("toolkit.startup.last_success", 1750703386);
user_pref("toolkit.telemetry.cachedClientID", "404f46fd-37ff-4366-aa96-43ff5dba4042");
user_pref("webchannel.allowObject.urlWhitelist", "");
