---
# Headscale configuration file
# See https://github.com/juanfont/headscale/blob/main/config-example.yaml for reference

# The url clients will connect to.
server_url: http://headscale:8080

# Address to listen to / bind to on the server
listen_addr: 0.0.0.0:8080

# Address to listen to /metrics, you may want to keep this endpoint private
metrics_listen_addr: 127.0.0.1:9090

# Path to the sqlite database file
db_type: sqlite3
db_path: /var/lib/headscale/db.sqlite

# Path to the private key file, generated automatically if it does not exist
private_key_path: /var/lib/headscale/private.key

# The Noise protocol private key is used to encrypt the
# traffic between the client and the server.
noise:
  private_key_path: /var/lib/headscale/noise_private.key

# List of IP prefixes to allocate tailaddresses from.
ip_prefixes:
  - fd7a:115c:a1e0::/48
  - 100.64.0.0/10

# DERP is a relay system that Tailscale uses when a direct
# connection cannot be established.
derp:
  server:
    enabled: false
    region_id: 999
    region_code: "headscale"
    region_name: "Headscale Embedded DERP"
    stun_listen_addr: "0.0.0.0:3478"
  
  # List of externally available DERP maps encoded in JSON
  urls:
    - https://controlplane.tailscale.com/derpmap/default
  
  # Locally available DERP map files encoded in YAML
  paths: []
  
  # If enabled, a worker will be set up to periodically
  # refresh the given sources and update the derpmap
  # will be set up.
  auto_update_enabled: true
  
  # How often should we check for DERP updates?
  update_frequency: 24h

# Disable the check for headscale updates on startup
disable_check_updates: false

# Maximum number of changes that we will accept
# when updating the acl policy
max_machine_namespace_count: 100

# DNS configuration
dns_config:
  # Whether to prefer using Headscale provided DNS
  # or use local system resolver
  override_local_dns: true
  
  # List of DNS servers to expose to clients.
  nameservers:
    - 1.1.1.1
    - 8.8.8.8
  
  # Domains to use for clients
  domains: []
  
  # Path to file containing DNS records
  # to serve to clients.
  magic_dns: true
  
  # Define the base domain to create the hostnames for MagicDNS.
  base_domain: example.com

# Unix socket used for the CLI to connect without authentication
# Note: for production, you might want to set this to a path like:
# unix_socket: /var/run/headscale/headscale.sock
unix_socket: /var/run/headscale.sock
unix_socket_permission: "0770"

# Path to the log file
log_level: info

# Path to the access control policy file
acl_policy_path: ""

# Logtail configuration
logtail:
  enabled: false
